title = "Simon MacDonald"
languageCode = "en-us"
baseURL = "https://macdonst.github.io/"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Simon MacDonald"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Simon MacDonald"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Speaking"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Simon MacDonald"
		subtitle   = "Father, Software Engineer, Comic Enthusiast and Coffee Lover"


	# About section
	[params.about]
		headline    = "We've got what you need!"
		description = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Praesentium similique eos eligendi error veritatis harum, sed aliquid totam, quam minus neque enim est architecto, ad. Maiores, aliquid, vitae!"
		buttonText  = "Get started!"


	# Service section
	[params.services]
		headline = "Contact Me"

    [[params.services.list]]
      icon = "fa-twitter"
      title = "Twitter"
      description = "Our templates are updated regularly so they don't break."

    [[params.services.list]]
			icon = "fa-github"
			title = "GitHub"
			description = "You can use this theme as is, or you can make changes!"

		[[params.services.list]]
      icon = "fa-instagram"
      title = "Instagram"
      description = "We update dependencies to keep things fresh."

    [[params.services.list]]
      icon = "fa-heart"
      title = "Made with Love"
      description = "You have to make your websites with love these days!"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Get the Creative Theme for Hugo"

		[params.aside.button]
			text = "Download now"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Contact Me"
		description = "Feel free to get in touch with me by one of these methods if you need to ask me a question or arrange for me to speak at an event."
    twitter = "macdonst"
    github = "macdonst"
    instagram = "macdonst"
    linkedin = "simonmacdonald"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
