title = "Simon MacDonald"
languageCode = "en-us"
baseURL = "https://macdonst.github.io/"
theme = "HugoMDL"
MetaDataFormat = "yaml"

[permalinks]
	page = "/:title/"
	about = "/:filename/"

[params]
  author = "Simon MacDonald"
  avatar = "/images/avatar.jpg"
  background = "/images/talk-bg.jpg"
  description = "A place to publish my incomprehensible ramblings" #meta description
  image = "/images/avatar-192.jpg" #for frontpage profile card
  mdlPrimary = "grey"
  mdlSecondary = "orange"
  website = "example.com"
  email = "Firstname@example.com"
  twitter = "https://twitter.com/macdonst"
  github = "https://github.com/macdonst/"
  linkedin = "https://linkedin.com/in/simonmacdonald/"
  copyrightyear = "2016"
  frontpageposts = 6 #number of post cards to display on frontpage

# Fully customizable header menu
[[menu.main]]
  name = "Home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Articles"
  url = "/post/"
  weight = -180
[[menu.main]]
  name = "Projects"
  url = "/project/"
  weight = -160
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = "-140"
