title = "Simon MacDonald"
languageCode = "en-us"
baseURL = "https://macdonst.github.io/"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Simon MacDonald"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Simon MacDonald"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Speaking"
			contact   = "Contact"
      blog      = "Blog"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Simon MacDonald"
		subtitle   = "Father, Software Engineer, Comic Enthusiast and Coffee Lover"


	# About section
	[params.about]
		headline    = "Who the heck is this guy?"
		description = "I'm a senior software developer working for Adobe where I contribute to open source projects like [Apache Cordova](https://cordova.apache.org/) and [Adobe PhoneGap](http://phonegap.com/). I've been lucky enough to speak at a number of conferences and meetups who's slide's and video's are archived here. As well, I'm one of the co-organizers of the ever popular [Ottawa JS Meetup](http://ottawajs.org/)."

	# Service section
	[params.services]
		headline = "Projects"

    [[params.services.list]]
      #icon = "fa-twitter"
      title = "Push Plugin"
      description = "Receive push notifications"
      url = "https://github.com/phonegap/phonegap-plugin-push"

    [[params.services.list]]
			#icon = "fa-github"
			title = "Content Sync"
			description = "Download and cache remotely hosted content"
      url = "https://github.com/phonegap/phonegap-plugin-contentsync"

		[[params.services.list]]
      #icon = "fa-instagram"
      title = "Image Editor"
      description = "Photo/Image editing tools"
      url = "https://github.com/CreativeSDK/phonegap-plugin-csdk-image-editor"

    [[params.services.list]]
      #icon = "fa-heart"
      title = "Speech Recognition"
      description = "Mobile speech recognition"
      url = "https://github.com/macdonst/SpeechRecognitionPlugin"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
#	[params.aside]
#		headline = "Get the Creative Theme for Hugo"
#
#		[params.aside.button]
#			text = "Download now"
#			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Contact Me"
		description = "Feel free to get in touch with me by one of these methods if you need to ask me a question or arrange for me to speak at an event."
    twitter = "macdonst"
    github = "macdonst"
    instagram = "macdonst"
    linkedin = "simonmacdonald"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
